language: node_js
cache:
  directories:
    - node_modules
node_js:
- lts/*
before_install:
- npm install -g semistandard
- npm install -g prettier
- npm install -g eslint
script:
- npm run linter
- npm run extractor
- npm run builder
- npm run packager
- npm run tester
- npm run test
- npm run vscoder
after_success:
- chmod +x .travis/push.sh
- .travis/push.sh
group: deprecated-2017Q4
