name: Deploy production
on:
  schedule:
    - cron: "20 18 * * *"
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run deployment script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        chmod +x ./src/scripts/deploy.sh
        ./src/scripts/deploy.sh production
